### ISSUE TITLE
Flutter 버전 불일치로 인한 경고 발생

### ISSUE THREAD

**Issue by hyeonjerry** [Dawon00/amigos_hackalearn#2]
버전 불일치로 인한 경고 발생
추후 발생할 수 있는 오류를 방지하기 위해 프로젝트 버전 업그레이드 진행

![KakaoTalk_20220807_231109733](https://user-images.githubusercontent.com/71651608/183400962-e630271c-df93-4de9-9510-3e37a8357de8.png)

현재 프로젝트 버전
```
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

댓글에 Flutter 버전 적어주세요.
모든 팀원 버전 확인 후 close 하겠습니다.

**Comment by Dawon00** [comment]
$ flutter --version
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

**Comment by kimwest00** [comment]
Flutter 3.0.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) •       
2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
