### ISSUE TITLE
Unexpected null value 오류

### ISSUE THREAD

**Issue by kimwest00** [Dawon00/amigos_hackalearn#3]
기능테스트를 위해 다음과 같이 main.dart의 home에서 호출하는 screen 함수를 수정하면 아래와 같은 오류가 뜹니다
해결 방법아시는분 계실까요?
```
Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Amigos',
      // home: LoginScreen(),
      home: IndexScreen(),
    );
  }
```

오류화면

![image](https://user-images.githubusercontent.com/71765938/183986173-75e95772-250e-4050-a043-3976565420eb.png)

오류메세지
ackages/flutter/src/widgets/framework.dart 4529:5                                                                             rebuild
packages/flutter/src/widgets/framework.dart 4787:5                                                                             [_firstBuild]
packages/flutter/src/widgets/framework.dart 4781:5                                                                             mount
packages/flutter/src/widgets/framework.dart 3817:15                                                                            inflateWidget
packages/flutter/src/widgets/framework.dart 3551:18                                                                            updateChild
packages/flutter/src/widgets/binding.dart 1202:16                                                                              [_rebuild]

**Comment by hyeonjerry** [comment]
오류 메시지 일부분
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown building IndexScreen(dirty, state: _IndexScreenState#182d2):
Unexpected null value.
The relevant error-causing widget was:
IndexScreen
lib\main.dart:35
When the exception was thrown, this was the stack:
...
packages/amigos_hackalearn/screen/index_screen.dart 42:73                            buildPageView
packages/amigos_hackalearn/screen/index_screen.dart 65:13                            build
...
```
index_screen.dart 파일의 42번 라인 buildPageView에서 오류가 발생했음을 확인할 수 있습니다.

index_screen.dart 42번 라인은 내 정보 화면인 my_page_screen.dart 파일의 MyPageScreen 클래스를 반환하는 것으로 보입니다.
이때, MyPageScreen은 로그인한 사용자의 uid를 인자로 받습니다.
하지만 로그인 페이지를 주석처리하여 로그인하지 않고 인덱스 페이지로 접속하게 되면 로그인한 사용자의 uid는 null이 됩니다.
이로 인하여 `Unexpected null value.` 오류가 발생한 것으로 보입니다.

해결 방법 1
42번 라인의 `child: MyPageScreen(uid: FirebaseAuth.instance.currentUser!.uid),` 부분을 `child: Container()`로 바꾸어 임시적으로 해결할 수 있으나 내 정보 페이지를 확인할 수 없습니다.

해결 방법 2
로그인 화면을 주석처리하지 않고 로그인을 진행하면 정상적으로 작동합니다.
임시로 생성한 계정의 id는 'email@naver.com'이며 비밀번호는 'password'입니다.
또한, sign up 기능이 정상적으로 작동하므로 개인적으로 계정을 만들어 로그인할 수도 있습니다.
