### ISSUE TITLE
사진 업로드 함수 위젯화

### ISSUE THREAD

**Issue by kimwest00** [Dawon00/amigos_hackalearn#4]
@Hyeonjae-K 작성하신 pickImage 함수를 post 기능에서도 사용하려고하는데
다른 dart파일에서도 접근할수있게 위젯화 시켜도될까요?
코드는 아래와 같습니다 
```
 Future pickImage(ImageSource source) async {
    final ImagePicker imagePicker = ImagePicker();

    XFile? file = await imagePicker.pickImage(source: source);

    if (file != null) {
      return await file.readAsBytes();
    }
  }
```

**Comment by hyeonjerry** [comment]
위젯화인가요?
함수를 공용으로 쓸 수 있도록 utils.dart 파일을 생성하여 해당 파일로 옮기는 것인가요?
@Dawon00

**Comment by Dawon00** [comment]
앱 전체에서 사용되는 기능이라면 utils 로 관리하는게 좋겠지만 
현재로써는 pickImage 함수는 회원가입 화면과 프로필 수정화면, 이렇게 2개의 화면에서만 쓰일예정이니
위젯화 하여 widget 폴더에서 관리해도 충분할 것 같습니다.

**Comment by hyeonjerry** [comment]
그럼 그렇게 구현하시면 될 것 같습니다.
