### ISSUE TITLE
post 모델 uid 필드 추가 요청

### ISSUE THREAD

**Issue by hyeonjerry** [Dawon00/amigos_hackalearn#7]
post 모델의 작성자 식별을 위한 uid 필드가 필요합니다.
author는 uid가 아닌 username이 들어가 있으므로 uid 필드를 새로 추가하여 게시글을 작성할 때 작성자의 uid도 함께 저장해 주세요.

**Comment by Dawon00** [comment]
post 모델(model/post.dart)에 uid 필드 추가하였습니다.

**Comment by kimwest00** [comment]
post기능(screen/post_screen.dart)에도 uid 정보 추가였습니다
