### ISSUE TITLE
post 생성시 Firebase에 저장되는 데이터 형식 수정 요청

### ISSUE THREAD

**Issue by Dawon00** [Dawon00/amigos_hackalearn#8]
![image](https://user-images.githubusercontent.com/71630722/184415395-71340fba-0041-4293-98ec-b0fd4386503f.png)

피드에서 게시물 리스트를 보여줄 때 게시물 마다 이미지를 출력해야합니다.
게시물을 생성할 때에 새로운 이미지를 선택해서 Firebase에 저장할 시, photoUrl 의 타입이 현재와는 다르게 url 형식이 되도록 수정해주세요.

**Comment by kimwest00** [comment]
url 형식으로 수정했으나 detail screen에서 확인해본 결과 사진이 아래와 같은 오류로 뜨지않습니다. 해결하고 다시 issue close 하도록 하겠습니다
![image](https://user-images.githubusercontent.com/71765938/184479829-d9ab83bf-91f6-4dac-a558-194abf8388a8.png)

**Comment by kimwest00** [comment]
flutter run -d chrome --web-renderer html 로 실행하여보니 정상적으로 작동합니다
