### ISSUE TITLE
post 생성시 post의 id 수정 필요

### ISSUE THREAD

**Issue by Dawon00** [Dawon00/amigos_hackalearn#9]
![image](https://user-images.githubusercontent.com/71630722/184419634-f4793fa2-32b0-47aa-9298-ce7c63cd8bb9.png)

현재 post 가 생성될 때마다 post의 id 값이 default 값인 "" 으로 저장되고 있습니다.
Firebase에서 자동으로 지정해주는 id 값이 생성된 post의 id 가 되도록 수정이 필요합니다.

**Comment by kimwest00** [comment]
post id의 경우 자동 생성 id말고 post 상태에따라 (생성,수정,삭제) 1,2,3으로 수정해도될까요?

**Comment by Dawon00** [comment]
유저가 생성한 게시물들을 모아보는 기능을 구현하기 위해서 post를 구별할 고유 id가 필요할 거라고 생각했습니다.
post 상태는 다른 필드로 관리하는게 좋지 않을까요?
@Hyeonjae-K 의견 듣고 싶습니다

**Comment by hyeonjerry** [comment]
> 유저가 생성한 게시물들을 모아보는 기능을 구현하기 위해서 post를 구별할 고유 id가 필요할 거라고 생각했습니다. post 상태는 다른 필드로 관리하는게 좋지 않을까요? @Hyeonjae-K 의견 듣고 싶습니다

유저가 생성한 게시물을 모아보는 기능은 uid 필드로 식별하는 것으로 이미 구현했습니다.
post의 id를 상태로 관리하는 것은 좋지 않아 보입니다.
